Add: README
Riri0000/Sharing_Kakeibo pull request #1
Opened 2020-11-26 02:10 UTC by Riri0000

## 概要
- `README`及び画面遷移図のラフ案を作成しました。

2020-11-26 06:42 UTC, yuji91 commented on README.md
> +
家計簿一覧の画面キャプチャがあると、一眼でアプリのイメージがついて良いかもしれません。
![image](https://user-images.githubusercontent.com/28836274/100316460-e7f8b680-2ffd-11eb-8d29-aab3bab2ab49.png)

2020-11-26 06:45 UTC, yuji91 commented on README.md
> +その中で、家計簿をつけ支出を把握することが家計を見直す第一歩だと感じており、家計簿に関するサービスを作りたいと思った。
少し長いので、以下の例のように短くできると読みやすくなりそうですね。
```suggestion
- 投資に失敗したことがきっかけで家計簿をつけ始め、家計簿ブログやTwitterを参考に支出を見直して生活するようになった。
家計を見直すことで資産が回復して不安がなくなり、前職を辞める勇気を持てた。
新たな挑戦をお金が後押ししてくれた経験があるので、お金と向き合うきっかけになるサービスが欲しいと思った。

家計簿をつけて支出を把握することが第一歩だと感じており、家計簿に関するサービスを作りたいと思った。
```

2020-11-26 06:46 UTC, yuji91 commented on README.md
> +- Twitterと連携し、匿名だからこそお金についてオープンに語り合うことのできるコミュニティが生まれる。
> オープンに語り合う

この辺り、アプリ内でコメントなど話し合える場があるのか、Twitter上で行うのかイメージ図があると伝わりやすそうですね。

2020-11-26 06:48 UTC, yuji91 commented on README.md
> +- 前職で、何百人もの税金滞納者の資産状況を調査してきたが、高収入であっても破産寸前の人が沢山いた。お金に興味がない人も他人の家計簿を見ることで自身を見直すきっかけにしてほしい（上からな感じ＆登場人物と外れるから削除するかも？）
伝え方を変えれば良さそうですね。
```suggestion
- 前職で、何百人もの税金滞納者の資産状況を調査してきたが、高収入であっても破産寸前の人が沢山いた。
他人の家計簿を見ることで、自身の家計を見直すきっかけにつながればと思う。
```

2020-11-26 06:48 UTC, yuji91 requested changes
ターゲットや目的が明確で良いと思います！

細かい文章の改善点を指摘したので、確認をお願いします。

2020-11-26 08:33 UTC, Mutsuki1102 commented on README.md
> +- ブログやTwitterで家計簿を公開する人達がいるが、情報を集約した場がない。
> - 他人の家計簿が気になる。資産運用が上手な人の支出内訳について知りたい。
こんな属性の方がいるんですね。あまりにも違う世界すぎてすごく興味がわきました。

2020-11-26 09:06 UTC, Riri0000 commented on README.md
> +
b552a2fad1ac8d0dc57214045ca7abcf748ad917 画面キャプチャを追加しました。

2020-11-26 09:07 UTC, Riri0000 commented on README.md
> +その中で、家計簿をつけ支出を把握することが家計を見直す第一歩だと感じており、家計簿に関するサービスを作りたいと思った。
f9eddad2d904c8554183a52806dd46987e9ac4a5 省略し、読みやすくしました。

2020-11-26 09:09 UTC, Riri0000 commented on README.md
> +- Twitterと連携し、匿名だからこそお金についてオープンに語り合うことのできるコミュニティが生まれる。
c6d89e4296a31a35aed0875709315d88e589987f 機能はできるだけシンプルにしたいので、コメント欄は設けず、Twitter上での交流を想定しています。Twitterでの交流風景を今後画面で載せたいと思います。

2020-11-26 09:10 UTC, Riri0000 commented on README.md
> +- 前職で、何百人もの税金滞納者の資産状況を調査してきたが、高収入であっても破産寸前の人が沢山いた。お金に興味がない人も他人の家計簿を見ることで自身を見直すきっかけにしてほしい（上からな感じ＆登場人物と外れるから削除するかも？）
0b8d67cbdc4afb91b334f2e15ef60602dd23992b 伝え方を柔らかくしました。

2020-11-26 10:43 UTC, DaichiSaito commented on README.md
> +- Vue.js 2.6.11
もうrubyは2.7系、Railsは6系でもいい気がする

2020-11-27 04:39 UTC, Riri0000 commented on README.md
> +- Vue.js 2.6.11
a81ca0077591e5cd13e92aeca8170781552cd0dc Ruby及びRailsのバージョンを更新しました。

2020-11-27 04:40 UTC, merged